# Generated by Django 2.2.14 on 2021-05-23 12:05

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OptionID', models.IntegerField()),
                ('OptionName', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_ID', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('prduct_name', models.CharField(max_length=200)),
                ('prduct_price', models.IntegerField()),
                ('product_imagepath', models.CharField(max_length=400)),
                ('product_update_date', models.DateField()),
                ('product_desciption', models.CharField(default='NONE', max_length=2000)),
                ('cout', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Product_categories',
            fields=[
                ('categories_ID', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('categories_Name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProductOption',
            fields=[
                ('ProductOption_ID', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('Option_Group_ID', models.IntegerField()),
                ('Option_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Option')),
                ('ProductID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Product_categories'),
        ),
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_ID', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('creation_date', models.DateField()),
                ('is_end', models.BooleanField()),
                ('products', models.ManyToManyField(to='home.Product')),
                ('seller_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-creation_date',),
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('products', models.ManyToManyField(to='home.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Customer')),
            ],
        ),
    ]
