# Generated by Django 2.2.14 on 2021-06-16 02:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0004_auto_20210526_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_desciption',
            field=models.CharField(default='NONE', max_length=10000),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_ID', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('context', models.CharField(max_length=2000)),
                ('product_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Product')),
                ('user_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
